---
- name: Install Docker
  hosts: aws_ec2
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        update_cache: yes
        state: present
    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

- name: Create new linux user for application
  hosts: aws_ec2
  become: yes
  vars_files:
    project-vars.yaml
  tasks:
    - name: Create user app
      user:
        name: "{{linux_name}}"
        comment: "Linux User"
        group: "{{user_groups}}"

- name: Install Docker Compose
  hosts: aws_ec2
  become: yes
  become_user: "{{linux_name}}"
  tasks:
    - name: Create docker-compose directory
      file:
        path: /root/.docker/cli-plugins
        state: directory
    - name: Get architecture of remote machine
      shell: uname -m
      register: architecture
    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{architecture.stdout}}"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x

- name: Start docker containers
  hosts: aws_ec2
  become: yes
  become_user: "{{linux_name}}"
  vars_files:
    project-vars.yaml
  tasks:
    - name: Copy docker-compose.yml to remote machine
      copy:
        src: /Users/danielnagorniy/Developer/DevOps/15_Ansible/ansible/docker-compose-full.yaml
        dest: "/home/{{linux_name}}/docker-compose.yml"
    - name: Docker login
      docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"
    - name: Start docker containers
      comunity.docker.docker_compose_v2:
        project_src: "/home/{{linux_name}}"
        state: present
